export const AUTH_LOGIN_PENDING = 'auth/login/pending'
export const AUTH_LOGIN_FULFILLED = 'auth/login/fulfilled'
export const AUTH_LOGIN_REJECTED = 'auth/login/rejected'
export const AUTH_LOGOUT = 'auth/logout'

export const SESSION_SAVE = 'session/save'

export const NOTIFICATION_CLOSE = 'notification/close'

export const MAX_PRICE = 'maxPrice'
//export const ADVERTS_GET = 'adverts/get'
export const ADVERTS_GET_PENDING = 'adverts/get/pending'
export const ADVERTS_GET_FULFILLED = 'adverts/get/fulfilled'
export const ADVERTS_GET_REJECTED = 'adverts/get/rejected'
export const ADVERTS_POST_PENDING = 'adverts/post/pending'
export const ADVERTS_POST_FULFILLED = 'adverts/post/fulfilled'
export const ADVERTS_POST_REJECTED = 'adverts/post/rejected'
export const ADVERTS_DELETE = 'adverts/delete'
export const TAGS_GET_PENDING = 'adverts/tags/pending'
export const TAGS_GET_FULFILLED = 'adverts/tags/fulfilled'
export const TAGS_GET_REJECTED = 'adverts/tags/rejected'

export const ADVERTS_DETAIL_PENDING = 'adverts/detail/pending'
export const ADVERTS_DETAIL_FULFILLED = 'adverts/detail/fulfilled'
export const ADVERTS_DETAIL_REJECTED = 'adverts/detail/rejected'
